SET ECHO ON
-- Effacement des tables. 

SET ECHO ON 

DROP TABLE Client CASCADE CONSTRAINTS;
DROP TABLE Corporatif CASCADE CONSTRAINTS;
DROP TABLE Categories CASCADE CONSTRAINTS;
DROP TABLE Fournisseurs CASCADE CONSTRAINTS;
DROP TABLE Article CASCADE CONSTRAINTS;
DROP TABLE Commande CASCADE CONSTRAINTS;
DROP TABLE LigneCommande CASCADE CONSTRAINTS;
DROP TABLE ConsulterCommandes CASCADE CONSTRAINTS;
DROP TABLE Livraison CASCADE CONSTRAINTS;
DROP TABLE LigneLivraison CASCADE CONSTRAINTS;
DROP TABLE Facture CASCADE CONSTRAINTS;
DROP TABLE Paiement CASCADE CONSTRAINTS;
DROP TABLE CarteCredit CASCADE CONSTRAINTS;
DROP TABLE Cheque CASCADE CONSTRAINTS;